### ISSUE TITLE
mirror name not consistent (ie: not used as variable) in create-ami.sh

### ISSUE THREAD

**Issue by anamorph** [ajacoutot/aws-openbsd#16]
L132:
``echo $MIRROR  >${_MNT}/etc/installurl``
instead of: 
``echo "https://ftp.fr.openbsd.org/pub/OpenBSD" >${_MNT}/etc/installurl``

**Comment by ajacoutot** [comment]
Hi @anamorph ;-)

That's by design for now.
Reason is that after a default installation, installurl should only contain an official mirror and we want to match a default installation as much as possible. That's especially true if your mirror is file://path/to/release/ ;-)
I am choosing ftp.fr for now but as you can see, there's an XXX to find a way to not hardcode this.
